### ISSUE TITLE
🐛 [Bug] Color of Hastags in Search Results

### ISSUE THREAD

**Issue by Mogge** [Yunite-Net/Yunite-Net-Ocelot-Social-Deploy-Rebranding#20]
## :bug: Bug Report
The color of the hashtags in the search result dropdown menu must be changed. It is hard to read as it is right now.

![image](https://user-images.githubusercontent.com/15882241/198258967-ae4616ad-ffc2-48fa-815d-8b050f3165cb.png)

**Comment by Tirokk** [comment]
solved by #21
