### ISSUE TITLE
🔧 [Refactor] Adapt the fonts

### ISSUE THREAD

**Issue by ogerly** [Yunite-Net/Yunite-Net-Ocelot-Social-Deploy-Rebranding#22]
## 🔧 Refactor
Adapt the fonts

**OVERPASS LIGHT**

**OVERPASS BOLD**

![image](https://user-images.githubusercontent.com/1324583/198716082-3585d717-59ee-4b07-8728-b8a3c81f6699.png)

**Comment by Tirokk** [comment]
The fonts are adapted now
